'use client';

import { FormEvent, useEffect, useState } from 'react';

type Product = { id:string; sku:string; name:string; slug:string; description:string|null; priceRwf:number; stock:number; imageUrl:string|null; isActive:boolean; category?:{id:string;name:string}|null; seller?:{id:string;businessName:string}|null };
type Category = { id:string; name:string };
type Seller = { id:string; businessName:string; status:string };

const empty = { sku:'', name:'', slug:'', description:'', priceRwf:'', stock:'0', imageUrl:'', categoryId:'', sellerId:'' };

export default function ProductsAdmin(){
 const [products,setProducts]=useState<Product[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [sellers,setSellers]=useState<Seller[]>([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<string|null>(null); const [message,setMessage]=useState(''); const [search,setSearch]=useState('');
 async function load(){ const [p,c,s]=await Promise.all([fetch('/api/products?admin=true',{cache:'no-store'}),fetch('/api/categories',{cache:'no-store'}),fetch('/api/sellers',{cache:'no-store'})]); setProducts((await p.json()).products??[]); setCategories((await c.json()).categories??[]); setSellers((await s.json()).sellers??[]); }
 useEffect(()=>{load()},[]);
 function edit(p:Product){setEditing(p.id);setForm({sku:p.sku,name:p.name,slug:p.slug,description:p.description??'',priceRwf:String(p.priceRwf),stock:String(p.stock),imageUrl:p.imageUrl??'',categoryId:p.category?.id??'',sellerId:p.seller?.id??''});window.scrollTo({top:0,behavior:'smooth'})}
 async function save(e:FormEvent){e.preventDefault();setMessage('');const body={...form,priceRwf:Number(form.priceRwf),stock:Number(form.stock),categoryId:form.categoryId||null,sellerId:form.sellerId||null};const r=await fetch(editing?`/api/products/${editing}`:'/api/products',{method:editing?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){setMessage(d.error??'Could not save product');return}setMessage(editing?'Product updated.':'Product created.');setEditing(null);setForm(empty);await load()}
 async function archive(id:string){if(!confirm('Archive this product?'))return;const r=await fetch(`/api/products/${id}`,{method:'DELETE'});if(r.ok){setMessage('Product archived.');await load()}}
 const visible=products.filter(p=>`${p.name} ${p.sku}`.toLowerCase().includes(search.toLowerCase()));
 return <main className="admin-page"><div className="admin-shell"><header className="admin-header"><div><div className="eyebrow">Gwizineza Market</div><h1>Product management</h1><p className="muted">Create, edit, price, stock, assign and archive products.</p></div><a className="btn btn-secondary" href="/admin">← Admin</a></header>
 <section className="admin-card"><h2>{editing?'Edit product':'Add product'}</h2><form className="form" onSubmit={save}><label>Product name</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label>SKU</label><input required value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})}/><label>Slug</label><input required value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><label>Description</label><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label>Price (RWF)</label><input required type="number" min="0" value={form.priceRwf} onChange={e=>setForm({...form,priceRwf:e.target.value})}/><label>Stock</label><input required type="number" min="0" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/><label>Category</label><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">No category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><label>Seller</label><select value={form.sellerId} onChange={e=>setForm({...form,sellerId:e.target.value})}><option value="">Gwizineza Market / no seller</option>{sellers.filter(s=>s.status==='APPROVED').map(s=><option key={s.id} value={s.id}>{s.businessName}</option>)}</select><label>Main image URL</label><input type="url" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} placeholder="https://..."/><div className="actions"><button className="btn btn-primary">{editing?'Update product':'Create product'}</button>{editing&&<button type="button" className="btn btn-secondary" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div></form>{message&&<p className="note">{message}</p>}</section>
 <section className="admin-card"><div className="actions"><h2>Products</h2><input placeholder="Search name or SKU" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="seller-list">{visible.map(p=><article className="seller-row" key={p.id}><div><strong>{p.name}</strong><div className="muted">{p.sku} · {p.priceRwf.toLocaleString()} RWF · Stock: {p.stock}</div><div className="muted">{p.category?.name??'No category'} · {p.seller?.businessName??'Marketplace'} · {p.isActive?'Active':'Archived'}</div></div><div className="seller-actions"><button className="btn btn-primary" onClick={()=>edit(p)}>Edit</button>{p.isActive&&<button className="btn btn-secondary" onClick={()=>archive(p.id)}>Archive</button>}</div></article>)}</div></section></div></main>
}
