'use client';
import { useEffect, useMemo, useState } from 'react';
type Product={id:string;name:string;priceRwf:number;stock:number;imageUrl:string|null;category:{name:string;slug:string}|null};
const money=(n:number)=>`${n.toLocaleString('en-US')} RWF`;
function createCartId(){const bytes=new Uint8Array(12);window.crypto.getRandomValues(bytes);return Array.from(bytes,byte=>byte.toString(16).padStart(2,'0')).join('')}
function getCartId(){const existing=localStorage.getItem('gwizineza-cart-id');if(existing&&/^[a-f0-9]{24}$/i.test(existing))return existing;const id=createCartId();localStorage.setItem('gwizineza-cart-id',id);return id}
export default function Shop(){const [products,setProducts]=useState<Product[]>([]);const [q,setQ]=useState('');const [category,setCategory]=useState('');const [categories,setCategories]=useState<{name:string;slug:string}[]>([]);const [cartId,setCartId]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(true);
useEffect(()=>{setCartId(getCartId());fetch('/api/categories',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>setCategories(d.categories??[])).catch(()=>setMessage('Categories could not be loaded.'))},[]);
useEffect(()=>{const params=new URLSearchParams();if(q)params.set('q',q);if(category)params.set('category',category);setLoading(true);fetch(`/api/products?${params}`,{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>setProducts(d.products??[])).catch(()=>{setProducts([]);setMessage('Products could not be loaded. Please refresh and try again.')}).finally(()=>setLoading(false))},[q,category]);
async function add(p:Product){if(!cartId){setMessage('Your cart is still loading. Please try again.');return}const r=await fetch('/api/cart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cartId,productId:p.id,quantity:1})});const d=await r.json();setMessage(r.ok?`${p.name} added to cart.`:(d.error??'Could not add product.'))}
const title=useMemo(()=>q?`Search results for “${q}”`:(category?`${category} products`:'All products'),[q,category]);return <main className="section"><div className="container"><header className="admin-header"><div><div className="eyebrow">Gwizineza Market</div><h1>Shop</h1><p className="muted">Search products or filter by category.</p></div><a className="btn btn-secondary" href="/">← Home</a></header><div className="actions"><input aria-label="Search products" placeholder="Search products..." value={q} onChange={e=>setQ(e.target.value)}/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select><a className="btn btn-primary" href="/#checkout">Cart</a></div>{message&&<div className="note">{message}</div>}<h2 style={{marginTop:28}}>{title}</h2>{loading?<p>Loading products...</p>:<><div className="products">{products.map(p=><article className="product" key={p.id}><div className="product-image">{p.imageUrl?<img src={p.imageUrl} alt={p.name}/>: '🛍️'}</div><div className="product-body"><div className="badge">{p.category?.name??'Featured'}</div><h3>{p.name}</h3><div className="price">{money(p.priceRwf)}</div><div className="muted">{p.stock} in stock</div><button className="btn btn-primary" style={{marginTop:14,width:'100%'}} disabled={!p.stock} onClick={()=>add(p)}>Add to cart</button></div></article>)}</div>{products.length===0&&<div className="note">No matching products found.</div>}</>}</div></main>}
